### ISSUE TITLE
Token permissions

### ISSUE THREAD

**Issue by cv65kr** [apisearch-io/search-server#111]
Hi,

If I good understood, token give access to CRUD operations on repository.
Anybody can saw source of my page and take API Code, and execute some operations. This should be protected in some way I guess, for example READ ONLY TOKEN.

Any ideas?

**Comment by mmoreram** [comment]
@cv65kr tokens can have many configurations.
One of these is the endpoints where the token can have access.

By default, any apisearch server installation will have, per configuration, one GOD_TOKEN, like a superadmin, a READ_ONLY_TOKEN and a PING_TOKEN, a token to make ping operations (for balancers, CDNs...)

:)

**Comment by cv65kr** [comment]
Thanks for response!
Documentation is still in progress, and everything is not clarify.
I will close this issue.
