### ISSUE TITLE
Null argument passed instead array

### ISSUE THREAD

**Issue by cv65kr** [apisearch-io/search-server#112]
Hi again,

Docker logs:
```
apisearch_server_0          | 200 POST   /v1/items (66 ms)
apisearch_server_0          | 200 GET    /v1 (3 ms)
apisearch_server_0          | 200 POST   /v1/items (51 ms)
apisearch_server_0          | 200 POST   /v1/items (83 ms)
apisearch_server_0          | 200 GET    /v1 (6 ms)
apisearch_server_0          | 200 GET    /v1 (5 ms)
apisearch_server_0          | {"message":"Argument 1 passed to Apisearch\\Query\\Query::createFromArray() must be of the type array, null given, called in \/var\/www\/apisearch\/Controller\/QueryController.php on line 70","code":0}%       
```

Tomorrow I will look at this, and send PR.

**Comment by cv65kr** [comment]
@mmoreram Can You review?
https://github.com/cv65kr/search-server/pull/1

Also You should block merging, this functionally should be only for repository owners :)

**Comment by cv65kr** [comment]
@mmoreram Can You review?

https://github.com/apisearch-io/search-server/pull/113

**Comment by mmoreram** [comment]
`Also You should block merging, this functionally should be only for repository owners :)`

What do you mean?

**Comment by mmoreram** [comment]
@cv65kr my appologies. Github is always a place where everythings seems worst that it seems.

To be clear, I am SUPER excitted with your reviews, issues and PRs :)
Lets build both these PR the best possible!

Thanks so much ! :1st_place_medal:

**Comment by cv65kr** [comment]
I see potential in this project, this will be great alternative for Algolia.
I try implement this as test on shop which I actually working on. Shop has a huge database, 400k products, 3k categories, and few's filters for all categories. That will be interesting! :+1:

**Comment by mmoreram** [comment]
Good morning!

After sleep time, I think that when this happens, instead of normalizing the situation by returning an empty array, we should return an exception. A malformatted query exception.

What do you think?

**Comment by cv65kr** [comment]
Hello!

Yes, this is better option, i will change this later.
