### ISSUE TITLE
Fix notices from symfony

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#167]
Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'The "apisearch_server.check_health_controller" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.' in /var/www/apisearch/vendor/symfony/dependency-injection/Container.php:282

Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'The "apisearch_server.get_indices_controller" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.' in /var/www/apisearch/vendor/symfony/dependency-injection/Container.php:282

Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'The "apisearch_server.create_index_controller" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.' in /var/www/apisearch/vendor/symfony/dependency-injection/Container.php:282

Noticed exception 'Ekino\NewRelicBundle\Exception\DeprecationException' with message 'The "apisearch_server.delete_index_controller" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.' in /var/www/apisearch/vendor/symfony/dependency-injection/Container.php:282

**Comment by mmoreram** [comment]
@hkulekci could you take a look at that?

**Comment by mmoreram** [comment]
@hkulekci the problem here is solved by disabling deprecations in NewRelic plugin

- https://github.com/apisearch-io/search-server/pull/168

We could try to solve this deprecation

**Comment by hkulekci** [comment]
#170 solves the deprecation exceptions.
