### ISSUE TITLE
SecurityPlugin

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#217]
Create a Security Plugin
- Token should have an array of variable parameters
- Put all token security part to this plugin
- Enable / Disable a Token
- Define the number of indices created by a token
- Add more features
    - Filters that can be applied
    - Fields that can be applied

## TOC
- [x] PHP Client Token metadata - https://github.com/apisearch-io/php-client/pull/70
- [x] Symfony Bundle commands changes - Changes not available in commands
- [x] Server commands changes - https://github.com/apisearch-io/search-server/pull/226
- [x] Security Bundle - https://github.com/apisearch-io/search-server/pull/226
- [x] Docs - Referenced in https://github.com/apisearch-io/search-server/issues/225

**Comment by hkulekci** [comment]
- return a security error response if the appId/token disabled. (without removing the appId or token)
- return a security error response if the appId exceed the request limits like 1M request in an expired time (one week, one month)
- return a security error response if the appId exceed the limit of the number of the index

**Comment by mmoreram** [comment]
Why do you mean by enabling or disabling an appId or a token?

**Comment by mmoreram** [comment]
@hkulekci check the first PR. Missing docs, but you can see something inside the tests :)

**Comment by hkulekci** [comment]
Enabling/disabling appId or token to use later we can disable token or appId without removing indices or appId related things. Then after some time, we can enable again and continue to use.  

Also, could we create a limitation for creating the index?

**Comment by mmoreram** [comment]
Updated Definition of Done.
