### ISSUE TITLE
Cannot filter on nested fields within nested fields

### ISSUE THREAD

**Issue by Goldfive** [apisearch-io/search-server#310]
Example:

`"clubCourses": [
        {
          "name": "Aeld",
          "details": {
            "general": {
              "nr_holes": 6,
              "handicap_course": "no"
            },
            "men": {
              "par_men_yellow": 62,
              "course_rating_men_yellow": 60.9,
              "slope_rating_men_yellow": 99,
              "length_men_yellow": 3960
            },
            "women": {
              "par_ladies_red": 62,
              "course_rating_ladies_red": 61.2,
              "slope_rating_ladies_red": 97,
              "length_ladies_red": 3460
            }
          }
        }
      ],`

This works: clubCourses.name
This doesn't: clubCourses.details.general.nr_holes

**Comment by mmoreram** [comment]
After some months, I think that that's the proper behavior.
Apisearch dataset should be designed in a flat way. The more flat is the model, the better in terms of performance. I would encourage you to find another way of modeling the domain in terms of data depth.

**Comment by mmoreram** [comment]
I close this issue, and if we find that this is a must, we can reopen it in the future.
Thanks!
