### ISSUE TITLE
Elasticsearch should be optional

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#326]
Without elasticsearch, we should be able to work without results. That means that we should be able to install Apisarch without dependencies, more focused on side projects testing (for example, the admin).

Of course, that means that we should be able to develop another search adapter, like Solr.

**Comment by hkulekci** [comment]
Could you describe these feature? How can this happen? So, this means that we can switch the search driver to other solutions like Solr, etc.?

**Comment by mmoreram** [comment]
Sure. I'll update the desc.

**Comment by mmoreram** [comment]
@hkulekci here you have the PR - https://github.com/apisearch-io/search-server/pull/327

- Some name changes (ElasticaPlugin => ElasticsearchPlugin) - Basically because I will start uncoupling from Elastica (the library) to go to pure PHP Elasticsearch (I'm not using anymore the Elastica client, only the model)
- As you can see, Elasticsearch is now optional. I created an InMemory adapter that basically makes everything but complex queries (only some basic filtering requested for tests - that can increase with testing coverage - and a bit of extra basic features)
- I moved some tests, so all the basic tests are passed using that InMemory adapter (basically, tests under `Tests/` folder are quite fast, and tests with Elasticsearch are placed under the Elasticsearch plugin. That will bring other search implementations to reuse these tests - placed in the domain as abstracts.
